version: '3.3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.25'
    #       memory: 16G
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.25'
    #       memory: 16G
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  # es03:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
  #   container_name: es03
  #   environment:
  #     - node.name=es03
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es02
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data03:/usr/share/elasticsearch/data
  #   networks:
  #     - elastic
  # es04:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
  #   container_name: es04
  #   environment:
  #     - node.name=es04
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es02,es03
  #     - cluster.initial_master_nodes=es01,es02,es03,es04
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data04:/usr/share/elasticsearch/data
  #   networks:
  #     - elastic
  kib01:
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic
  logstash:
    container_name: logstash
    image: logstash:7.16.3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.template.json:/usr/share/logstash/templates/logstash.template.json
      - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml 
    ports:
      - 5044:5044
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
  # logstash2:
  #   container_name: logstash2
  #   image: logstash:7.16.3
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - ./logstash2.conf:/usr/share/logstash/pipeline/logstash.conf
  #     - ./logstash.template2.json:/usr/share/logstash/templates/logstash.template.json
  #     - ./pipelines2.yml:/usr/share/logstash/config/pipelines.yml 
  #   ports:
  #     - 5045:5045
  #   environment:
  #     ELASTICSEARCH_URL: http://es02:9200
  #     ELASTICSEARCH_HOSTS: http://es02:9200
  #   networks:
  #     - elastic
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "50"
  # logstash3:
  #   container_name: logstash3
  #   image: logstash:7.16.3
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - ./logstash3.conf:/usr/share/logstash/pipeline/logstash.conf
  #     - ./logstash3.template.json:/usr/share/logstash/templates/logstash.template.json
  #     - ./pipelines3.yml:/usr/share/logstash/config/pipelines.yml 
  #   ports:
  #     - 5046:5046
  #   environment:
  #     ELASTICSEARCH_URL: http://es03:9200
  #     ELASTICSEARCH_HOSTS: http://es03:9200
  #   networks:
  #     - elastic
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "50"
  filebeat:
    user: root
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.16.3
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - ./mylog:/usr/share/filebeat/mylog
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: ["--strict.perms=false"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      mode: global
    environment:
      LOGSTASH_URL: http://logstash:5044
      LOHSTASH_HOSTS: http://logstash:5044
    networks:
      - elastic
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
  # filebeat2:
  #   user: root
  #   container_name: filebeat2
  #   image: docker.elastic.co/beats/filebeat:7.16.3
  #   volumes:
  #     - /var/run/docker.sock:/host_docker/docker.sock
  #     - /var/lib/docker:/host_docker/var/lib/docker
  #     - ./mylog2:/usr/share/filebeat/mylog
  #     - ./filebeat2.yml:/usr/share/filebeat/filebeat.yml
  #   command: ["--strict.perms=false"]
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   deploy:
  #     mode: global
  #   environment:
  #     LOGSTASH_URL: http://logstash2:5045
  #     LOHSTASH_HOSTS: http://logstash2:5045
  #   networks:
  #     - elastic
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "50"
  # filebeat3:
  #   user: root
  #   container_name: filebeat3
  #   image: docker.elastic.co/beats/filebeat:7.16.3
  #   volumes:
  #     - /var/run/docker.sock:/host_docker/docker.sock
  #     - /var/lib/docker:/host_docker/var/lib/docker
  #     - ./mylog3:/usr/share/filebeat/mylog
  #     - ./filebeat3.yml:/usr/share/filebeat/filebeat.yml
  #   command: ["--strict.perms=false"]
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   deploy:
  #     mode: global
  #   environment:
  #     LOGSTASH_URL: http://logstash3:5046
  #     LOHSTASH_HOSTS: http://logstash3:5046
  #   networks:
  #     - elastic
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "50"

volumes:
  data01:
    driver: local
  data02:
    driver: local
  # data03:
  #   driver: local
  # data04:
  #   driver: local

networks:
  elastic:
    driver: bridge