filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/log_gen/y.log

output.logstash:
  hosts: ["logstash2:5045"]

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"
